MODEL:
  model_name: 'CLIPSegP'
  clipseg_hf_api: "CIDAS/clipseg-rd64-refined"

DATASET:
  dataset_name: 'kvasir'
  num_classes: 2
  root_dir: "data_process/kvasir"

TRAIN:
  device: 'cuda:0'
  random_seed: 666
  input_size: 224
  train_data_ratio: 1.0

  batch_size: 16
  num_workers: 4
  epochs: 500
  lr: 0.0003
  warmup_lr: 0.00003
  warmup_epoch: 0
  patience: 50

  print_freq: 150
  start_epoch: 0
  save_best: True
  amp: True